services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
  api:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis

volumes:
  redis:
    driver: local
